import Head from 'next/head'
import { useEffect } from 'react';
import { app } from '@/app';
import WList from '@/widgets/list';

export default function Home({ todos }: any) {
  app.storeBusiness.global.hydrateTodos(todos);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <WList />
    </>
  )
}

export const getServerSideProps = async () => {
  await app.storeBusiness.global.getTodos();

  return {
    props: {
      todos: app.storeBusiness.global.todos
    }
  };
}
